name: Deploy Angular App

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: Explorer

    - name: Build Angular project
      run: npm run build --prod
      working-directory: Explorer

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        aws-region: us-east-1

    - name: Sync to S3
      uses: jakejarvis/s3-sync-action@v1.3.0
      with:
        args: --acl public-read --delete
      env:
        SOURCE_DIR: './Explorer/dist' # Change to your Angular build output directory
        TARGET_DIR: 's3://dipl-explorer-frontend-bucket' # Replace with your S3 bucket name

    - name: Invalidate CloudFront cache
      uses: chetangowda/cloudfront-invalidation-action@v2
      with:
        distribution-id: 'E3NKFQT21KWKOO'
        paths: '/*'
